export default [
  {
    text: "软考",
    items: [
      { text: "首页", link: "./index" },
      { text: "第1章 信息化发展", link: "./chapter-1" },
      { text: "第2章 信息技术发展", link: "./chapter-2" },
      { text: "第3章 信息系统治理", link: "./chapter-3" },
      { text: "第4章 信息系统管理", link: "./chapter-4" },
      { text: "第5章 信息系统工程", link: "./chapter-5" },
      { text: "第6章 项目管理概论", link: "./chapter-6" },
      { text: "第7章 项目立项管理", link: "./chapter-7" },
      { text: "第8章 项目整合管理", link: "./chapter-8" },
      { text: "第9章 项目范围管理", link: "./chapter-9" },
      { text: "第10章 项目进度管理", link: "./chapter-10" },
      { text: "第11章 项目成本管理", link: "./chapter-11" },
      { text: "第12章 项目质量管理", link: "./chapter-12" },
      { text: "第13章 项目资源管理", link: "./chapter-13" },
      { text: "第14章 项目沟通管理", link: "./chapter-14" },
      { text: "第15章 项目风险管理", link: "./chapter-15" },
      { text: "第16章 项目采购管理", link: "./chapter-16" },
      { text: "第17章 项目干系人管理", link: "./chapter-17" },
      { text: "第18章 项目绩效域", link: "./chapter-18" },
      { text: "第19章 配置与变更管理", link: "./chapter-19" },
      { text: "第20章 高级项目管理", link: "./chapter-20" },
      { text: "第21章 项目管理科学基础", link: "./chapter-21" },
      { text: "第22章 组织通用治理", link: "./chapter-22" },
      { text: "第23章 组织通用管理", link: "./chapter-23" },
      { text: "第24章 法律法规与标准规范", link: "./chapter-24" },
      { text: "知识整合", link: "./important" },
    ],
  },
];
